project_id = "riubtdbaqjyronitywbs"

[functions.send-whatsapp]
verify_jwt = false

[functions.send-signed-document-email]
verify_jwt = false

[functions.agendar-entrevista]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.enviar-lembretes]
verify_jwt = false

[functions.extrair-certidao]
verify_jwt = false

[functions.extrair-matricula]
verify_jwt = false

[functions.send-interview-result-email]
verify_jwt = false

[functions.distribuir-tarefa-email]
verify_jwt = false

[functions.enhance-text]
verify_jwt = true
